baseURL = "https://blog.aliavanoglu.com/"
languageCode = "tr"
title = "Ali Avanoğlu — Blog"
theme = "PaperMod"

paginate = 10
enableRobotsTXT = true

[params]
  author = "Ali Avanoğlu"
  description = "Koşu, üretkenlik, teknoloji ve girişimcilik üzerine notlar"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]  # JSON ileride arama için işimize yarar

[permalinks]
  posts = "/:slug/"

[menu]
  [[menu.main]]
    name = "Yazılar"
    url  = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Hakkında"
    url  = "/about/"
    weight = 2

