baseURL = "https://blog.aliavanoglu.com/"
languageCode = "tr"
title = "Çocuk ürolojisi İzmir - Prof. Dr. Ali AVANOĞLU Blog Sayfası"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "Prof. Dr. Ali Avanoğlu"
  description = "Çocuk Ürolojisi ve Doğuştan Anomaliler Hakkında Ebeveynleri Bilgilendirici ve Anlaşılır Makaleler."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  env = "production"

  [params.profileMode]
    enabled = true
    title = "Çocuk Ürolojisi ve Doğuştan Anomaliler Hakkında Ebeveynleri Bilgilendirici ve Anlaşılır Makaleler"
    subtitle = "<br/>- Prof. Dr. Ali AVANOĞLU<br/><small><br/>-Bu site çocukların doğuştan üroloji anomalilerinin tedavisine adanmıştır.</small>"
    imageUrl = "/img/Ali_Avanoglu.webp"
    imageTitle = "Prof. Dr. Ali Avanoğlu"
    imageWidth = 180
    imageHeight = 180
    buttons = [
      { name = "Makaleler", url = "/posts/" },
      { name = "Hakkımda",  url = "/about/" }
    ]

[outputs]
  home = ["HTML","RSS","JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Hakkımda"
    url  = "/about/"
    weight = 1
  [[menu.main]]
    name = "Makaleler"
    url  = "/posts/"
    weight = 2
  [[menu.main]]
    name = "KVKK"
    url  = "/kvkk/"
    weight = 3
  [[menu.main]]
    name = "İletişim"
    url  = "/iletisim/"
    weight = 4
