baseURL = "http://127.0.0.1:1316/"
languageCode = "tr"
title = "Ali Avanoğlu — Blog"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "Ali Avanoğlu"
  description = "Koşu, üretkenlik, teknoloji ve girişimcilik üzerine notlar"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[outputs]
  home = ["HTML","RSS","JSON"]
