baseURL = "https://blog.aliavanoglu.com/"
languageCode = "tr"
title = "Çocuk Ürolojisi İzmir — Prof. Dr. Ali AVANOĞLU"
theme = "PaperMod"
enableRobotsTXT = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10

[params]
  author = "Prof. Dr. Ali Avanoğlu"
  description = "Çocuk Ürolojisi ve Doğuştan Anomaliler Hakkında Ebeveynleri Bilgilendirici ve Anlaşılır Makaleler."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  env = "production"

  # Sosyal paylaşım/OG için kapak görseli
  images = ["/img/kapak-og.webp"]

  # Ana sayfa profil/hero bloğu
  [params.profileMode]
    enabled = true
    title = "Çocuk Ürolojisi İzmir — Prof. Dr. Ali AVANOĞLU"
    subtitle = "Çocuk Ürolojisi ve Doğuştan Anomaliler Hakkında Ebeveynleri Bilgilendirici ve Anlaşılır Makaleler<br/><small>Bu site çocukların doğuştan üroloji anomalilerinin tedavisine adanmıştır.</small>"
    imageUrl = "/img/Ali_Avanoglu-180.webp"
    imageTitle = "Prof. Dr. Ali Avanoğlu"
    imageWidth = 180
    imageHeight = 180
    buttons = [
      { name = "Makaleler", url = "/posts/" },
      { name = "Hakkımda",  url = "/about/" }
    ]

[outputs]
  home = ["HTML","RSS","JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Hakkımda"
    url  = "/about/"
    weight = 1
  [[menu.main]]
    name = "Makaleler"
    url  = "/posts/"
    weight = 2
  [[menu.main]]
    name = "KVKK"
    url  = "/kvkk/"
    weight = 3
  [[menu.main]]
    name = "İletişim"
    url  = "/iletisim/"
    weight = 4
