baseURL = "https://blog.aliavanoglu.com/"
languageCode = "tr"
defaultContentLanguage = "tr"
title = "Çocuk Ürolojisi İzmir — Prof. Dr. Ali AVANOĞLU"
theme = "PaperMod"
enableRobotsTXT = true
[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Prof. Dr. Ali Avanoğlu"
  description = "Çocuk Ürolojisi ve Doğuştan Anomaliler Hakkında Ebeveynleri Bilgilendirici ve Anlaşılır Makaleler."
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = true

# İsteğe bağlı: menü (PaperMod uyumlu)
[menu]

  [[menu.main]]
    name = "Hakkımda"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Makaleler"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "KVKK"
    url = "/kvkk/"
    weight = 30

  [[menu.main]]
    name = "İletişim"
    url = "/iletisim/"
    weight = 40
