
baseURL = "http://127.0.0.1:1314/"  # lokal için böyle dursun; yayında blog.aliavanoglu.com olacak
languageCode = "tr"
title = "Ali Avanoğlu — Blog"
theme = "PaperMod"
[pagination]
  pagerSize = 10

enableRobotsTXT = true

[params]
  author = "Ali Avanoğlu"
  description = "Koşu, üretkenlik, teknoloji ve girişimcilik üzerine notlar"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

