baseURL = "https://blog.aliavanoglu.com/"
languageCode = "tr"
title = "Çocuk Ürolojisi — Bilgi ve Rehber"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "Ali Avanoğlu"
  description = "Çocuk ürolojisi: inmemiş testis, hipospadias, vezikoüreteral reflü (VUR), sünnet, gece alt ıslatma, böbrek ve idrar yolu hastalıkları hakkında kanıta dayalı bilgiler."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  env = "production"

  # Ana sayfa kahraman metni (PaperMod)
  [params.homeInfoParams]
    Title = "Çocuk Ürolojisi"
    Content = "Aileler için anlaşılır, hekimler için titiz: inmemiş testis, hipospadias, VUR ve diğer çocuk ürolojisi konuları."

[outputs]
  home = ["HTML","RSS","JSON"]

# Taksonomiler
[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Blog"
    url  = "/posts/"
    weight = 1
  [[menu.main]]
    name = "SSS"
    url  = "/sss/"
    weight = 2
  [[menu.main]]
    name = "Hakkında"
    url  = "/about/"
    weight = 3
  [[menu.main]]
    name = "İletişim"
    url  = "/iletisim/"
    weight = 4
